const HttpCons = {
  ERROR_INFO: {
    SHOW_SELECT_DATA_NULL: "选择列表参数为空",
    CALL_REQUEST_URI_NULL: "请求的URI为空",
    CALL_REQUEST_DATA_NOT_JSON: "请求的数据不是一个json",
    HTTP_FETCH_ONCALLBACK_RESPONSE_NULL: "HTTP_FETCH响应信息为空",
    HTTP_FETCH_ONCALLBACK_RESPONSE_INFO_NULL: "HTTP_FETCH响应的INFO为空",
    HTTP_FETCH_ONCALLBACK_RESPONSE_DATA_NULL: "HTTP_FETCH响应的DATA为空",
    HTTP_FETCH_ONCALLBACK_RESPONSE_BIZ_DATA_NULL: "HTTP_FETCH响应的BIZDATA为空",
    HTTP_FETCH_ONCALLBACK_RESPONSE_CANCEL: "HTTP_FETCH响应为取消状态",
    HTTP_FETCH_ONCALLBACK_RESPONSE_ERROR: "HTTP_FETCH响应为错误状态",
    HTTP_FETCH_ONCALLBACK_RESPONSE_TIMEOUT: "请求超时",
    HTTP_FETCH_ONCALLBACK_RESPONSE_UNKNOWN: "未知错误"
  }
}

export default HttpCons;
